#:schema node_modules/wrangler/config-schema.json
name = "homeschool-app"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "homeschool_db"
database_id = "local"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = ".next"
pages_build_output_dir = ".next"
